apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  labels:
    kustomize.component: iap-ingress
  name: ingress-jwt
  namespace: istio-system
spec:
  origins:
  - jwt:
      issuer: jlewi@google.com
      jwksUri: https://storage.googleapis.com/issue-label-bot-dev_public/chatbot/keys/jwk-sig-chatbot-pub.jwk
      audiences:
      - kubeflow-chatbot
      trigger_rules:
      - included_paths:
        - prefix: /chatbot
  - jwt:    
      audiences:
      - /projects/976279526634/global/backendServices/9003463958197541329
      issuer: https://cloud.google.com/iap
      jwksUri: https://www.gstatic.com/iap/verify/public_key-jwk
      jwtHeaders:
      - x-goog-iap-jwt-assertion
      trigger_rules:
      - excluded_paths:
        - exact: /healthz/ready
  principalBinding: USE_ORIGIN
  targets:
  - name: istio-ingressgateway
    ports:
    - number: 80
