apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service-account.yaml
images:
- digest: sha256:ce3feb1b3f8f27bacd122a50e8df8582204c2eade6854daca47c02a3ca748a6d
  name: gcr.io/issue-label-bot-dev/labelbot-diff
  newName: gcr.io/issue-label-bot-dev/labelbot-diff:4e60ec4
