# https://cloud.google.com/ai-platform/deep-learning-containers/docs/choosing-container
FROM gcr.io/deeplearning-platform-release/pytorch-cpu.1-4

RUN pip install \
    fire==0.3.1 \
    simpletransformers==0.48.15
