# This package defines the overlays of all GCP infra
# config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace should match the project.
# This assumes we are running CNRM in namespace mode and namespaces match project names.
namespace: issue-label-bot-dev # {"type":"string","x-kustomize":{"setBy":"kpt","partialSetters":[{"name":"gcloud.core.project","value":"issue-label-bot-dev"}]}}
# TODO(jlewi): do not commit the labels auto-deploy and purpose; they were added
# as part of autodeployment testing.
commonLabels:
  kf-name: code-intelligence # {"type":"string","x-kustomize":{"setter":{"name":"name","value":"code-intelligence"}}}
resources:
- ../../upstream/manifests/gcp/v2/cnrm
- iam_policy.yaml
- nodepool.yaml
patchesStrategicMerge:
- cluster_patch.yaml
